language: rust
dist: bionic
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

addons:
  apt:
    packages:
      - llvm-7
      - llvm-7-*
      - lld-7

script:
  - cargo build --verbose --all
  - cargo test --verbose --all -- --test-threads=1
