[package]
name = "mun_syntax"
version = "0.2.0"
authors = ["The Mun Team <team@mun-lang.org>"]
edition = "2018"
homepage = "https://mun-lang.org"
repository = "https://github.com/mun-lang/mun"
license = "MIT OR Apache-2.0"
description = "Parsing functionality for the Mun programming language"

[dependencies]
rowan = "0.6.1"
text_unit = { version = "0.1.6", features = ["serde"] }
smol_str = { version = "0.1.12", features = ["serde"] }
unicode-xid = "0.1.0"
drop_bomb = "0.1.4"
mun_errors = { path = "../mun_errors"}

[dev-dependencies]
insta = "0.12.0"
