[package]
name = "mun_project"
version = "0.1.0"
authors = ["Wodann <remco.kuijper@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mun_runtime = { path = "../mun_runtime" }
