[package]
name = "tools"
version = "0.2.0"
authors = ["The Mun Team <team@mun-lang.org>"]
edition = "2018"

[dependencies]
teraron = "0.0.1"
clap = "2.32.0"
failure = "0.1.7"
ron = "0.4.2"
cbindgen = { git = "https://github.com/baszalmstra/cbindgen", branch = "fix_lockfile_v2" }
bindgen = "0.51"
difference = "2.0"
