[package]
name = "mun_test"
version = "0.1.0"
authors = ["Wodann <remco.kuijper@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
mun_symbols = { path = "../mun_symbols" }
lazy_static = "1.3"
parking_lot = "0.9"
