[package]
name = "mun_memory"
version = "0.1.0"
authors = ["Wodann <wodannson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
abi = { path = "../mun_abi", package = "mun_abi" }
once_cell = "1.3.1"
parking_lot = "0.10"
lazy_static = "1.4.0"

[dev-dependencies]
paste = "0.1"
