[package]
name = "mun_memory"
version = "0.1.0"
authors = ["Wodann <wodannson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
abi = { path = "../mun_abi", package = "mun_abi" }
